<?xml version="1.0"?>

<robot name="tracer_v1"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_1.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_2.xacro" />

    <xacro:include filename="$(find tracer_description)/urdf/fr_castor.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/fl_castor.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rr_castor.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rl_castor.xacro" />

    <xacro:include filename="$(find tracer_description)/urdf/fr_wheel.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/fl_wheel.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rr_wheel.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rl_wheel.xacro" />

    <xacro:include filename="$(find myarm_description)/urdf/myarm_m/mc_frame.xacro" />
    <xacro:include filename="$(find myarm_description)/urdf/myarm_m/myarm_m1.xacro" />
    <xacro:include filename="$(find myarm_description)/urdf/myarm_m/myarm_m2.xacro" />
    <xacro:include filename="$(find myarm_description)/urdf/myarm_c650/myarm_c1.xacro" />
    <xacro:include filename="$(find myarm_description)/urdf/myarm_c650/myarm_c2.xacro" />



    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.34"/><!--0.33515-->
    <xacro:property name="track" value="0.37910" /><!--0.37810-->

    <xacro:property name="castor_length" value="0.002"/>
    <xacro:property name="castor_radius" value="0.03724" />

  <xacro:property name="wheel_vertical_offset" value="-0.082" />
  <xacro:property name="castor_offset" value="0.03" />

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <link name="base_footprint" />
    <joint name="base_footprint_base_link" type="fixed">
        <origin xyz="0 0 0.15" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
            <geometry>
                <mesh filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
          <geometry>
            <mesh
              filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="132.3898489950015" />
            <origin xyz="0.015 0.0231316650320557 0" />

            <inertia ixx="0.185196122711036"
            ixy="4.30144213829512E-08"
            ixz="5.81037523686401E-08"
            iyy="0.364893736238929"
            iyz="-0.000386720198091934"
            izz="0.223868521722778" />
        </inertial>
    </link>

    <!-- 固定连接 小车和型材-->
    <joint name="base_link_to_car_frame" type="fixed">
        <origin xyz="-0.14 0 -0.006" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="profile_frame_base" />
    </joint>

    <joint name="m1_base_to_car_frame" type="fixed">
        <origin xyz="0.4 0.265 0.95" rpy="0 0 0" />
        <parent link="profile_frame_base" />
        <child link="m1_base" />
    </joint>

    <joint name="m2_base_to_car_frame" type="fixed">
        <origin xyz="0.4 -0.265 0.95" rpy="0 0 0" />
        <parent link="profile_frame_base" />
        <child link="m2_base" />
    </joint>

    <joint name="c1_base_to_car_frame" type="fixed">
        <origin xyz="-0.695 0.315 0.89" rpy="0 0 0" />
        <parent link="profile_frame_base" />
        <child link="c1_base" />
    </joint>

    <joint name="c2_base_to_car_frame" type="fixed">
        <origin xyz="-0.695 -0.315 0.89" rpy="0 0 0" />
        <parent link="profile_frame_base" />
        <child link="c2_base" />
    </joint>


    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <xacro:tracer_wheel_1 wheel_prefix="right">
        <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:tracer_wheel_1>
    <xacro:tracer_wheel_2 wheel_prefix="left">
        <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:tracer_wheel_2>

<!--tracer castor wheel-->

    <xacro:fl_castor wheel_prefix="fl_castor">
        <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:fl_castor>
    <xacro:fr_castor wheel_prefix="fr_castor">
        <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:fr_castor>
    <xacro:rr_castor wheel_prefix="rr_castor">
        <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:rr_castor>
    <xacro:rl_castor wheel_prefix="rl_castor">
        <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:rl_castor>

    <xacro:fl_wheel wheel_prefix="fl">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:fl_wheel>
    <xacro:fr_wheel wheel_prefix="fr">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:fr_wheel>
    <xacro:rr_wheel wheel_prefix="rr">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:rr_wheel>
    <xacro:rl_wheel wheel_prefix="rl">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:rl_wheel>




    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find tracer_description)/urdf/tracer.gazebo" />
</robot>
